# Generated by Django 4.2.16 on 2024-12-07 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(),
        ),
    ]
