# Generated by Django 4.2.16 on 2024-11-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_property_options_tenant_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantapprovalrequest',
            options={'verbose_name': 'Tenant Approval Request', 'verbose_name_plural': 'Tenant Approval Requests'},
        ),
        migrations.RemoveConstraint(
            model_name='tenantapprovalrequest',
            name='tenant_property_belongs_to_landlord',
        ),
    ]
