# Generated by Django 4.2.16 on 2024-11-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_landlordprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandlordProfile',
        ),
    ]
