# Generated by Django 4.2.16 on 2024-11-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_property_landlord_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.landlord'),
        ),
    ]
