# Generated by Django 4.2.16 on 2024-11-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_property_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(db_index=True, default='null@null.null', max_length=254),
        ),
    ]
